### ISSUE TITLE
Icon proposal

### ISSUE THREAD

**Issue by Zabriskije** [bentettmar/barnotes#6]
Hi @bentettmar,
I've made two icons for your app. If you like it, feel free to use it ;)

<img width="128" src="https://user-images.githubusercontent.com/101254295/162452937-a80a196c-3411-4c00-86e6-3295f3b5e0d2.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/162453023-bae6b0fa-5c87-4966-b0e3-83f6d7e13a1e.png">

PNG + ICNS: [MenuNote.zip](https://github.com/MenuNote/menunote/files/8452584/MenuNote.zip)

**Comment by bennyscripts** [comment]
Those are amazing! Thanks so much for doing that. I'll consider using them. If I use them I'll make sure to credit your name.

**Comment by Zabriskije** [comment]
Thanks! Glad you like it 🥳
